# Configuration for Cloudflare Pages
name = "haircutfun-com"
compatibility_date = "2024-01-01"

# Disable telemetry for cleaner build output
send_metrics = false

# Pages configuration
pages_build_output_dir = "out"

# Disable any deploy commands - this is a Pages project, not Workers
[vars]
SKIP_DEPLOY = "true"