name = "haircutfun"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "haircutfun"

[[env.production.routes]]
pattern = "*"
zone_name = "your-domain.com"