name = "haircutfun"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# OpenNext Cloudflare configuration
main = ".open-next/cloudflare/worker.js"

# Assets configuration
[assets]
directory = ".open-next/assets"

# Environment variables
[vars]
# Add your environment variables here

[env.production]
name = "haircutfun"

[[env.production.routes]]
pattern = "*"
zone_name = "your-domain.com"